begin;

create extension if not exists "pgcrypto";

-- Enumerations
DO $$
BEGIN
  CREATE TYPE public.app_locale AS ENUM ('en', 'zh-CN', 'id-ID');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE public.login_result AS ENUM ('success', 'failed');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Core identity and RBAC tables
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  full_name text,
  locale public.app_locale not null default 'en',
  timezone text not null default 'Asia/Jakarta',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  deleted_at timestamptz
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  is_system boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  module text not null,
  action text not null,
  description text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.role_permission_relations (
  role_id bigint not null references public.roles (id) on delete cascade,
  permission_id bigint not null references public.permissions (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (role_id, permission_id)
);

create table if not exists public.user_role_relations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  role_id bigint not null references public.roles (id) on delete cascade,
  assigned_by uuid references public.profiles (id) on delete set null,
  assigned_at timestamptz not null default timezone('utc', now()),
  unique (user_id, role_id)
);

-- Shared capability tables
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  entity_type text,
  entity_id text,
  is_read boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.operation_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles (id) on delete set null,
  module text not null,
  entity_type text not null,
  entity_id text,
  action text not null,
  before_data jsonb,
  after_data jsonb,
  meta jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.login_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles (id) on delete set null,
  email text,
  result public.login_result not null,
  ip text,
  user_agent text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.app_uploaded_files (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles (id) on delete cascade,
  bucket_id text not null,
  object_path text not null,
  file_name text not null,
  mime_type text,
  size_bytes bigint,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.dictionary_items (
  id bigint generated by default as identity primary key,
  dictionary_type text not null,
  code text not null,
  label text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (dictionary_type, code)
);

-- Indexes
create index if not exists idx_notifications_user_read_created on public.notifications (user_id, is_read, created_at desc);
create index if not exists idx_operation_logs_module_created on public.operation_logs (module, created_at desc);
create index if not exists idx_operation_logs_entity on public.operation_logs (entity_type, entity_id);
create index if not exists idx_login_logs_user_created on public.login_logs (user_id, created_at desc);
create index if not exists idx_uploads_owner_created on public.app_uploaded_files (owner_id, created_at desc);

-- Trigger function for updated_at
create or replace function public.set_updated_at_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at_timestamp();

drop trigger if exists trg_roles_set_updated_at on public.roles;
create trigger trg_roles_set_updated_at
before update on public.roles
for each row
execute function public.set_updated_at_timestamp();

drop trigger if exists trg_permissions_set_updated_at on public.permissions;
create trigger trg_permissions_set_updated_at
before update on public.permissions
for each row
execute function public.set_updated_at_timestamp();

drop trigger if exists trg_dictionary_set_updated_at on public.dictionary_items;
create trigger trg_dictionary_set_updated_at
before update on public.dictionary_items
for each row
execute function public.set_updated_at_timestamp();

-- Auto profile bootstrap on auth user creation
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_default_role_id bigint;
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, coalesce(new.email, ''), new.raw_user_meta_data ->> 'full_name')
  on conflict (id) do update
    set email = excluded.email,
        full_name = coalesce(excluded.full_name, public.profiles.full_name);

  select id into v_default_role_id from public.roles where code = 'bd_user' limit 1;

  if v_default_role_id is not null then
    insert into public.user_role_relations (user_id, role_id)
    values (new.id, v_default_role_id)
    on conflict (user_id, role_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_auth_user();

-- RBAC helper functions
create or replace function public.is_super_admin(target_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_role_relations urr
    join public.roles r on r.id = urr.role_id
    where urr.user_id = coalesce(target_user_id, auth.uid())
      and r.code = 'super_admin'
  );
$$;

create or replace function public.has_permission(permission_code text, target_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_role_relations urr
    join public.role_permission_relations rpr on rpr.role_id = urr.role_id
    join public.permissions p on p.id = rpr.permission_id
    where urr.user_id = coalesce(target_user_id, auth.uid())
      and p.code = permission_code
  )
  or public.is_super_admin(target_user_id);
$$;

create or replace function public.record_login(
  p_result public.login_result,
  p_email text default null,
  p_user_agent text default null,
  p_ip text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.login_logs (user_id, email, result, ip, user_agent)
  values (auth.uid(), p_email, p_result, p_ip, p_user_agent);
end;
$$;

create or replace function public.record_operation_log(
  p_module text,
  p_entity_type text,
  p_entity_id text default null,
  p_action text default null,
  p_before_data jsonb default null,
  p_after_data jsonb default null,
  p_meta jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.operation_logs (
    actor_id,
    module,
    entity_type,
    entity_id,
    action,
    before_data,
    after_data,
    meta
  )
  values (
    auth.uid(),
    p_module,
    p_entity_type,
    p_entity_id,
    coalesce(p_action, 'update'),
    p_before_data,
    p_after_data,
    p_meta
  );
end;
$$;

create or replace function public.assign_role_by_email(p_email text, p_role_code text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_role_id bigint;
begin
  select id into v_user_id
  from public.profiles
  where lower(email) = lower(p_email)
  limit 1;

  if v_user_id is null then
    raise exception 'Profile not found for email: %', p_email;
  end if;

  select id into v_role_id
  from public.roles
  where code = p_role_code
  limit 1;

  if v_role_id is null then
    raise exception 'Role not found for code: %', p_role_code;
  end if;

  insert into public.user_role_relations (user_id, role_id)
  values (v_user_id, v_role_id)
  on conflict (user_id, role_id) do nothing;
end;
$$;

-- Seed roles and permissions
insert into public.roles (code, name, description, is_system)
values
  ('super_admin', 'Super Admin', 'Global administration role', true),
  ('bd_user', 'BD User', 'Lead and onboarding initiator role', true),
  ('project_manager', 'Project Manager', 'Project execution owner role', true)
on conflict (code) do update
  set name = excluded.name,
      description = excluded.description;

insert into public.permissions (code, module, action, description)
values
  ('users.read', 'users', 'read', 'Read users list and profile summary'),
  ('users.write', 'users', 'write', 'Manage users and lifecycle status'),
  ('roles.assign', 'roles', 'assign', 'Assign and revoke user roles'),
  ('logs.read', 'logs', 'read', 'Read operation and login logs'),
  ('files.upload', 'files', 'upload', 'Upload and manage private files'),
  ('notifications.read', 'notifications', 'read', 'Read notifications'),
  ('leads.read', 'leads', 'read', 'Read lead data'),
  ('leads.write', 'leads', 'write', 'Write lead data'),
  ('onboarding.read', 'onboarding', 'read', 'Read onboarding cases'),
  ('onboarding.write', 'onboarding', 'write', 'Write onboarding cases'),
  ('projects.read', 'projects', 'read', 'Read project data'),
  ('projects.write', 'projects', 'write', 'Write project data')
on conflict (code) do update
  set module = excluded.module,
      action = excluded.action,
      description = excluded.description;

-- Role-permission mapping
insert into public.role_permission_relations (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on 1 = 1
where r.code = 'super_admin'
on conflict do nothing;

insert into public.role_permission_relations (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on p.code in (
  'leads.read',
  'leads.write',
  'onboarding.read',
  'onboarding.write',
  'notifications.read',
  'files.upload',
  'projects.read'
)
where r.code = 'bd_user'
on conflict do nothing;

insert into public.role_permission_relations (role_id, permission_id)
select r.id, p.id
from public.roles r
join public.permissions p on p.code in (
  'projects.read',
  'projects.write',
  'onboarding.read',
  'notifications.read',
  'files.upload',
  'leads.read'
)
where r.code = 'project_manager'
on conflict do nothing;

-- Dictionary seeds
insert into public.dictionary_items (dictionary_type, code, label, sort_order, is_active)
values
  ('lead_status', 'NEW', 'New', 10, true),
  ('lead_status', 'TO_FOLLOW', 'To Follow', 20, true),
  ('lead_status', 'FOLLOWING', 'Following', 30, true),
  ('lead_status', 'NEGOTIATING', 'Negotiating', 40, true),
  ('lead_status', 'ON_HOLD', 'On Hold', 50, true),
  ('lead_status', 'LOST', 'Lost', 60, true),
  ('lead_status', 'SIGNED', 'Signed', 70, true),
  ('onboarding_status', 'NOT_STARTED', 'Not Started', 10, true),
  ('onboarding_status', 'INFO_PENDING', 'Info Pending', 20, true),
  ('onboarding_status', 'DOCUMENT_PENDING', 'Document Pending', 30, true),
  ('onboarding_status', 'UNDER_REVIEW', 'Under Review', 40, true),
  ('onboarding_status', 'REVISION_REQUIRED', 'Revision Required', 50, true),
  ('onboarding_status', 'CONTRACT_CONFIRMED', 'Contract Confirmed', 60, true),
  ('onboarding_status', 'SERVICE_ACTIVATING', 'Service Activating', 70, true),
  ('onboarding_status', 'COMPLETED', 'Completed', 80, true),
  ('onboarding_status', 'REJECTED', 'Rejected', 90, true),
  ('project_status', 'NOT_STARTED', 'Not Started', 10, true),
  ('project_status', 'IN_PROGRESS', 'In Progress', 20, true),
  ('project_status', 'ON_HOLD', 'On Hold', 30, true),
  ('project_status', 'DELAYED', 'Delayed', 40, true),
  ('project_status', 'COMPLETED', 'Completed', 50, true),
  ('project_status', 'CLOSED', 'Closed', 60, true)
on conflict (dictionary_type, code) do update
  set label = excluded.label,
      sort_order = excluded.sort_order,
      is_active = excluded.is_active;

-- Grants
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update on public.profiles to authenticated;
grant select on public.roles, public.permissions, public.role_permission_relations, public.dictionary_items to authenticated;
grant select, insert, delete on public.user_role_relations to authenticated;
grant select, insert, update on public.notifications to authenticated;
grant select, insert, delete on public.app_uploaded_files to authenticated;
grant select on public.operation_logs, public.login_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated, service_role;

grant execute on function public.is_super_admin(uuid) to authenticated;
grant execute on function public.has_permission(text, uuid) to authenticated;
grant execute on function public.record_login(public.login_result, text, text, text) to authenticated;
grant execute on function public.record_operation_log(text, text, text, text, jsonb, jsonb, jsonb) to authenticated;
grant execute on function public.assign_role_by_email(text, text) to authenticated;

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.role_permission_relations enable row level security;
alter table public.user_role_relations enable row level security;
alter table public.notifications enable row level security;
alter table public.operation_logs enable row level security;
alter table public.login_logs enable row level security;
alter table public.app_uploaded_files enable row level security;
alter table public.dictionary_items enable row level security;

-- Profiles policies
DROP POLICY IF EXISTS profiles_select_self_or_admin ON public.profiles;
create policy profiles_select_self_or_admin
on public.profiles
for select
to authenticated
using (auth.uid() = id or public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS profiles_insert_self_or_admin ON public.profiles;
create policy profiles_insert_self_or_admin
on public.profiles
for insert
to authenticated
with check (auth.uid() = id or public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS profiles_update_self_or_admin ON public.profiles;
create policy profiles_update_self_or_admin
on public.profiles
for update
to authenticated
using (auth.uid() = id or public.is_super_admin(auth.uid()))
with check (auth.uid() = id or public.is_super_admin(auth.uid()));

-- Roles and permissions policies
DROP POLICY IF EXISTS roles_select_authenticated ON public.roles;
create policy roles_select_authenticated
on public.roles
for select
to authenticated
using (true);

DROP POLICY IF EXISTS roles_manage_admin ON public.roles;
create policy roles_manage_admin
on public.roles
for all
to authenticated
using (public.is_super_admin(auth.uid()))
with check (public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS permissions_select_authenticated ON public.permissions;
create policy permissions_select_authenticated
on public.permissions
for select
to authenticated
using (true);

DROP POLICY IF EXISTS permissions_manage_admin ON public.permissions;
create policy permissions_manage_admin
on public.permissions
for all
to authenticated
using (public.is_super_admin(auth.uid()))
with check (public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS role_permission_select_authenticated ON public.role_permission_relations;
create policy role_permission_select_authenticated
on public.role_permission_relations
for select
to authenticated
using (true);

DROP POLICY IF EXISTS role_permission_manage_admin ON public.role_permission_relations;
create policy role_permission_manage_admin
on public.role_permission_relations
for all
to authenticated
using (public.is_super_admin(auth.uid()))
with check (public.is_super_admin(auth.uid()));

-- User-role relation policies
DROP POLICY IF EXISTS user_role_select_self_or_admin ON public.user_role_relations;
create policy user_role_select_self_or_admin
on public.user_role_relations
for select
to authenticated
using (user_id = auth.uid() or public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS user_role_manage_admin ON public.user_role_relations;
create policy user_role_manage_admin
on public.user_role_relations
for all
to authenticated
using (public.is_super_admin(auth.uid()))
with check (public.is_super_admin(auth.uid()));

-- Notification policies
DROP POLICY IF EXISTS notifications_select_own ON public.notifications;
create policy notifications_select_own
on public.notifications
for select
to authenticated
using (user_id = auth.uid() or public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS notifications_insert_self_or_admin ON public.notifications;
create policy notifications_insert_self_or_admin
on public.notifications
for insert
to authenticated
with check (user_id = auth.uid() or public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS notifications_update_own ON public.notifications;
create policy notifications_update_own
on public.notifications
for update
to authenticated
using (user_id = auth.uid() or public.is_super_admin(auth.uid()))
with check (user_id = auth.uid() or public.is_super_admin(auth.uid()));

-- Operation logs policies
DROP POLICY IF EXISTS operation_logs_select_admin ON public.operation_logs;
create policy operation_logs_select_admin
on public.operation_logs
for select
to authenticated
using (public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS operation_logs_insert_self_or_admin ON public.operation_logs;
create policy operation_logs_insert_self_or_admin
on public.operation_logs
for insert
to authenticated
with check (actor_id = auth.uid() or public.is_super_admin(auth.uid()));

-- Login logs policies
DROP POLICY IF EXISTS login_logs_select_admin ON public.login_logs;
create policy login_logs_select_admin
on public.login_logs
for select
to authenticated
using (public.is_super_admin(auth.uid()));

-- Uploaded files policies
DROP POLICY IF EXISTS uploaded_files_select_owner_or_admin ON public.app_uploaded_files;
create policy uploaded_files_select_owner_or_admin
on public.app_uploaded_files
for select
to authenticated
using (owner_id = auth.uid() or public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS uploaded_files_insert_owner_or_admin ON public.app_uploaded_files;
create policy uploaded_files_insert_owner_or_admin
on public.app_uploaded_files
for insert
to authenticated
with check (owner_id = auth.uid() or public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS uploaded_files_delete_owner_or_admin ON public.app_uploaded_files;
create policy uploaded_files_delete_owner_or_admin
on public.app_uploaded_files
for delete
to authenticated
using (owner_id = auth.uid() or public.is_super_admin(auth.uid()));

-- Dictionary policies
DROP POLICY IF EXISTS dictionary_select_authenticated ON public.dictionary_items;
create policy dictionary_select_authenticated
on public.dictionary_items
for select
to authenticated
using (true);

DROP POLICY IF EXISTS dictionary_manage_admin ON public.dictionary_items;
create policy dictionary_manage_admin
on public.dictionary_items
for all
to authenticated
using (public.is_super_admin(auth.uid()))
with check (public.is_super_admin(auth.uid()));

-- Storage bucket and object policies
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'private-documents',
  'private-documents',
  false,
  20971520,
  array['application/pdf', 'image/png', 'image/jpeg', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
)
on conflict (id) do nothing;

DROP POLICY IF EXISTS private_documents_select ON storage.objects;
create policy private_documents_select
on storage.objects
for select
to authenticated
using (
  bucket_id = 'private-documents'
  and (
    split_part(name, '/', 1) = auth.uid()::text
    or public.is_super_admin(auth.uid())
  )
);

DROP POLICY IF EXISTS private_documents_insert ON storage.objects;
create policy private_documents_insert
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'private-documents'
  and split_part(name, '/', 1) = auth.uid()::text
);

DROP POLICY IF EXISTS private_documents_delete ON storage.objects;
create policy private_documents_delete
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'private-documents'
  and (
    split_part(name, '/', 1) = auth.uid()::text
    or public.is_super_admin(auth.uid())
  )
);

commit;
