-- Store tier field on leads + configurable store-alert rule thresholds.
-- Additive only: new enum, new column with safe default, new admin-only config table.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'store_tier') then
    create type public.store_tier as enum ('KA', 'NORMAL');
  end if;
end $$;

alter table public.leads
  add column if not exists store_tier public.store_tier not null default 'NORMAL';

create table if not exists public.store_alert_rule_config (
  id bigint generated by default as identity primary key,
  tier public.store_tier not null unique,
  no_visit_days integer not null default 7 check (no_visit_days > 0),
  no_deal_visit_count integer not null default 2 check (no_deal_visit_count > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists trg_store_alert_rule_config_set_updated_at on public.store_alert_rule_config;
create trigger trg_store_alert_rule_config_set_updated_at
before update on public.store_alert_rule_config
for each row
execute function public.set_updated_at_timestamp();

insert into public.store_alert_rule_config (tier, no_visit_days, no_deal_visit_count)
values ('NORMAL', 7, 2), ('KA', 3, 2)
on conflict (tier) do nothing;

alter table public.store_alert_rule_config enable row level security;

drop policy if exists store_alert_rule_config_select_admin on public.store_alert_rule_config;
create policy store_alert_rule_config_select_admin
on public.store_alert_rule_config
for select
to authenticated
using (public.is_super_admin(auth.uid()));

drop policy if exists store_alert_rule_config_manage_admin on public.store_alert_rule_config;
create policy store_alert_rule_config_manage_admin
on public.store_alert_rule_config
for all
to authenticated
using (public.is_super_admin(auth.uid()))
with check (public.is_super_admin(auth.uid()));

grant select, insert, update on public.store_alert_rule_config to authenticated;
grant usage, select on sequence public.store_alert_rule_config_id_seq to authenticated;
